day19/sky/sky/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [

    path('admin/', admin.site.urls),
    path('order/',include('order.urls')),
    path('',include('user.urls')),


    #xxx/category/1
]

day19/sky/user/models.py
from django.db import models

# Create your models here.

#分类表、文章表

class BaseModel(models.Model):
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    update_time = models.DateTimeField(verbose_name='修改时间',auto_now=True)

    class Meta:
        abstract = True


class Category(BaseModel):
    name = models.CharField(verbose_name='分类名称',max_length=50,unique=True)

    class Meta:
        db_table = 'category'
        verbose_name = '文章分类'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']

    def __str__(self):
        return self.name

class Article(BaseModel):
    title = models.CharField(verbose_name='文章标题',max_length=100,)
    content = models.TextField(verbose_name='文章内容') #长文本类型
    read_count = models.IntegerField(verbose_name='阅读次数',default=0)
    category = models.ForeignKey(Category,on_delete=models.PROTECT,verbose_name='分类')  #外键
    #models.DO_NOTHING #什么也不干
    #models.CASCADE ,会删除
    #models.SET_DEFAULT ，设置一个默认值，1
    #models.SET_NULL #设置成空
    #models.PROTECT#受保护的，如果还有在使用的，不能让你删除
    #models.SET#自定义模式，自己指定

    class Meta:
        db_table = 'article'
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']

    def __str__(self):
        return self.title

class Teacher(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'teacher'

class Student(models.Model):
    name = models.CharField(max_length=50,verbose_name='学生姓名')
    teacher = models.ManyToManyField(Teacher,verbose_name='老师')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'student'

class Case(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=10)
    method = models.CharField(max_length=20)
    param = models.CharField(max_length=30)
    require_case = models.ForeignKey('self',on_delete=models.PROTECT,verbose_name='依赖用例',null=True,blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'case'
        ordering = ['-id']



class Account(models.Model):
    balance = models.IntegerField(verbose_name='余额',default=0)

    class Meta:
        db_table = 'account'

class User(models.Model):
    name = models.CharField(max_length=50)
    account = models.OneToOneField(Account,on_delete=models.CASCADE,verbose_name='账户')#级联

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'user'


class Interface(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=50,unique=True)
    response = models.TextField(default='{}',null=True,blank=True,verbose_name='返回报文')


    def __str__(self):
        return self.name

    class Meta:
        db_table = 'interface'
        verbose_name = "接口"
        verbose_name_plural = verbose_name


class Sku(BaseModel):
    name = models.CharField(max_length=50,verbose_name='工具名称')
    price = models.IntegerField(verbose_name='价格',)
    count = models.IntegerField(verbose_name='数量',default=10,null=True,blank=True)
    color = models.CharField(max_length=50,verbose_name='颜色')

    class Meta:
        verbose_name = '商品表'
        verbose_name_plural = verbose_name
        ordering = ['-update_time']
        db_table = 'sku'

day19/sky/templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="/add" method="post">
    {% csrf_token %}
    <div>title:<input name="title"></div>

    <div>content<textarea name="content"></textarea></div>

    <select name="category_id">
        {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}

    </select>

    <button type="submit">提交</button>

</form>

</body>
</html>

day19/sky/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="referrer" content="origin">
    <!-- TDK and ICO -->
    <title>{{ title }}</title>

    <meta name="description"
          content="TendCode是一个Django搭建的博客，本网站后端使用Django框架搭建，前端使用Bootstrap框架，主要分享博主在Python以及其他编程语言的学习心得。">
    <meta name="keywords" content="Python自学,Python爬虫,Django博客,Python web开发,个人博客">
    <!--站长验证-->

    <link rel="shortcut icon" href="/static/blog/img/favicon.ico" type="image/x-icon"/>
    <!-- Bootstrap and font-awesome CSS -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="/static/js/headroom.min.js"></script>
    <!-- blog CSS -->
    <link href="/static/css/base.css" rel="stylesheet">
    {% block css %}
    {% endblock %}

    <!--根据cookies判断是否启用暗色主题-->

</head>
<body>
<!--导航开始-->

<nav class="navbar navbar-expand-md bg-white fixed-top blog-navbar py-md-0">
    <a class="navbar-brand d-md-none d-lg-block" id="site-logo-name" href="/">
        <strong class="px-2">{{ title }}</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-2">

                <a class="nav-link py-md-3 active" href="/"><i class="fa fa-home mr-1"></i>首页<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-2">

                <a class="nav-link py-md-3 " href="./archive.html"><i class="fa fa-sitemap mr-1"></i>归档</a>
            </li>



            <form class="nav-item navbar-form mr-2 py-md-2" role="search" method="get" id="searchform"
                  action="/search/">
                <div class="input-group">
                    <input type="search" name="q" class="form-control rounded-0" placeholder="站内搜索" autocomplete="off"
                           required=True>
                    <div class="input-group-btn">
                        <button class="btn btn-info rounded-0" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </div><!-- /input-group -->
            </form>
        </ul>

    </div>
</nav>

<!--导航结束-->

<!--消息块-->


<!--回到顶部按钮-->
<div class="text-center" id="to-top">
    <i class="fa fa-chevron-up" id="btn-top" title="回到顶部"></i>
</div>

<!--主要内容块-->
<main>
    <div class="container">
        <div class="row">

            {% block body %}

            {% endblock %}


            <div class="col-lg-4">


                <!--个人空间-->
                <div class="card border-0 rounded-0 px-3 mb-2 mb-md-3 d-none d-lg-block" id="home-card">
                    <div class="card-header bg-white px-0">
                        <strong><i class="fa fa-paper-plane mr-2 f-17"></i>个人空间</strong>
                    </div>
                    <div class="card-body px-0 pt-3 pb-1">
                        <div class="row text-center">
                            <div class="col">
                                <a href="https://github.com/Hopetree" target="_blank" title="进入博主的Github查看博客源码">
                                    <img style="max-width:40px" alt="博主的github" src="https://tendcode.com/static/blog/img/github.png">
                                    <p class="mt-2">Github</p>
                                </a>
                            </div>
                            <div class="col">
                                <a href="/timeline/" target="_blank" title="查看网站建站历程">
                                    <img style="max-width:40px" alt="网站的建站历程" src="https://tendcode.com/static/blog/img/blog.png">
                                    <p class="mt-2">Timeline</p>
                                </a>
                            </div>

                            <div class="col">
                                <a href="/timeline/" target="_blank" title="查看网站建站历程">
                                    <img style="max-width:40px" alt="网站的建站历程" src="https://tendcode.com/static/blog/img/blog.png">
                                    <p class="mt-2">Timeline</p>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
                <!--文章分类-->
                <div class="card border-0 rounded-0 px-3 mb-2 mb-md-3" id="category-card">
                    <div class="card-header bg-white px-0">
                        <strong><i class="fa fa-book mr-2 f-17"></i>文章分类</strong>
                    </div>

                    <ul class="list-group list-group-flush f-16">

                        {% for category in categories %}

                        <li class="list-group-item d-flex justify-content-between align-items-center pr-2 py-2">
                            <a class="category-item" href="/category/{{ category.id }}"
                               title="查看【CI/CD】分类下所有文章">{{ category.name }}</a>
                            <span class="badge text-center" title="当前分类下有{{ category.article_set.count }}篇文章">
                                {{ category.article_set.count }}</span>
                        </li>

                        {% endfor %}


                    </ul>
                </div>
                <!--标签云-->
                <div class="card border-0 rounded-0 px-3 mb-2 mb-md-3" id="tag-card">
                    <div class="card-header bg-white px-0">
                        <strong><i class="fa fa-tags mr-2 f-17"></i>标&nbsp;签&nbsp;云</strong>
                    </div>
                    <div class="card-body px-0 py-3">
                        <div class="tag-cloud">

                            {% for tag in tag_list %}
                            <a href="/tag/Virtualenv/" class="tags f-16" id="tag-1"
                               title="【Virtualenv】标签下有3篇文章">{{ tag }}</a>
                            {% endfor %}



                        </div>
                    </div>
                </div>
                <!--友链-->
                <div class="d-none d-lg-block">
                    <div class="card border-0 rounded-0 px-3 mb-2 mb-md-3" id="friends-card">
                        <div class="card-header bg-white px-0">
                            <strong><i class="fa fa-link mr-2 f-17"></i>友情链接</strong>
                        </div>
                        <div class="card-body px-0 py-3">
                            <div class="tool-list">


                                <div class="w-50 float-left text-center mb-2">
                                    <div class="mx-2">
                                        <a href="https://github.com/Hopetree/izone" title="izone 博客项目的源代码"
                                           target="_blank">
                                            博客源码</a>
                                    </div>
                                </div>

                                <div class="w-50 float-left text-center mb-2">
                                    <div class="mx-2">
                                        <a href="https://frostming.com" title="一个基于 Flask 开发的博客" target="_blank">
                                            Frost&#39;s Blog</a>
                                    </div>
                                </div>

                                <div class="w-50 float-left text-center mb-2">
                                    <div class="mx-2">
                                        <a href="https://zmrenwu.com" title="Django 博客教程分享者" target="_blank">
                                            追梦人物</a>
                                    </div>
                                </div>

                                <div class="w-50 float-left text-center mb-2">
                                    <div class="mx-2">
                                        <a href="https://www.dusaiphoto.com/" title="Django 搭建的博客，分享博客教程"
                                           target="_blank">
                                            杜赛的个人网站</a>
                                    </div>
                                </div>

                                <div class="w-50 float-left text-center mb-2">
                                    <div class="mx-2">
                                        <a href="https://www.jerrycoding.com/" title="Jerry 的个人博客" target="_blank">
                                            Jerry Coding</a>
                                    </div>
                                </div>

                                <div class="w-50 float-left text-center mb-2">
                                    <div class="mx-2">
                                        <a href="https://boywithacoin.cn/" title="Stray_Camel的个人技术博客" target="_blank">
                                            Stray_Camel</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<!--js cookie 插件-->
<script src="/static/js/js.cookie.min.js?v=20191123.12"></script>
<script src="https://cdn.bootcss.com/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% block js %}
{% endblock %}
<script>
    $(function () {
        var myElement = document.querySelector(".blog-navbar");
        var headroom = new Headroom(myElement);
        headroom.init()
    });
</script>
<script src="/static/js/base.js?v=20191123.0909890"></script>


<footer class="container-fluid mt-4 py-0">
    <div class="card-body text-center px-0 f-14">
        <p class="card-text mb-1">Copyright&nbsp;&copy;&nbsp;<span id="year-info"></span>
           &nbsp;Powered&nbsp;by&nbsp;Django.
        </p>


    </div>
</footer>
</body>
</html>

day19/sky/templates/category.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-lg-8">
        <div class="description bg-white px-3 pt-3 pb-1">
            <p class="float-right mb-0">共<span class="mx-2 text-info">{{ articles.count }}</span>篇</p>
            <h1 class="f-17"><strong>文章分类：{{ articles.first.category.name }}</strong></h1>
            <p class="f-16">CI/CD 是一种通过在应用开发阶段引入自动化来频繁向客户交付应用的方法。CI/CD 的核心概念是持续集成、持续交付和持续部署。具体而言，CI/CD
                在整个应用生命周期内（从集成和测试阶段，到交付和部署）引入了持续自动化和持续监控。</p>
        </div>
        <div class="text-secondary font-weight-bold py-2 f-15 choice">


            <a class="pb-2 active" href="/category/ci-cd/">
                <i class="fa fa-bars mr-1"></i>时间排序</a>

        </div>


        <div class="summary-list">

            {% for art in articles %}


                <div class="media mb-1 mb-sm-2 p-2 p-lg-3">
                    <div class="align-self-center mr-2 mr-lg-3 w-25 modal-open">
                        <a href="/detail/{{ art.id }}" target="_blank">
                            <img class="w-100 article-img" src="https://tendcode.com/cdn/article/190710/jenkins.png"
                                 alt="【Jenkins 插件】Jenkins Pipeline 流水线插件的使用，Vue 项目自动化构建和部署实战">
                        </a>
                    </div>
                    <div class="media-body">

                        <div class="text-muted mb-2 f-12">


                            <img class="avatar"
                                 src="https://tendcode.com/media/avatar/2019/07/27/91ef76c6a7efce1b99717f97a851f3deb48f6510.png"
                                 alt="Hopetree">

                            <span>Hopetree</span>
                            <span><i class="fa fa-calendar-times-o ml-2 mr-1"></i>2月，3&nbsp;周前</span>
                        </div>
                        <h2 class="mt-0 font-weight-bold text-info f-17">
                            <a href="/detail/{{ art.id }}" target="_blank">{{ art.title }}</a>
                        </h2>
                        <p class="d-none d-sm-block mb-2 f-15">{{ art.content }}</p>
                        <div class="text-muted mb-0 f-12">
                            <a class="cate" href="/category/{{ art.category.id }}" title="查看当前分类下更多文章">
                                <i class="fa fa-book mr-1"></i>{{ art.category.name }}</a>
                            <span><i class="fa fa-eye ml-2 mr-1"></i>{{ art.read_count }}</span>
                            <a href="/article/Jenkins-Pipeline/#comment-block" target="_blank" title="查看文章评论">
                                <i class="fa fa-comments ml-2 mr-1"></i>5</a>
                        </div>
                    </div>
                </div>


            {% endfor %}


        </div>


    </div>

{% endblock %}

day19/sky/templates/detail.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="referrer" content="origin">
    <!-- TDK and ICO -->
    <title>Tend to Code_一个使用django和bootstrap搭建的个人博客_TendCode</title>

    <meta name="description"
          content="TendCode是一个Django搭建的博客，本网站后端使用Django框架搭建，前端使用Bootstrap框架，主要分享博主在Python以及其他编程语言的学习心得。">
    <meta name="keywords" content="Python自学,Python爬虫,Django博客,Python web开发,个人博客">
    <!--站长验证-->

    <link rel="shortcut icon" href="/static/blog/img/favicon.ico" type="image/x-icon"/>
    <!-- Bootstrap and font-awesome CSS -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="/static/js/headroom.min.js"></script>
    <!-- blog CSS -->
    <link href="/static/css/base.css" rel="stylesheet">
    <link href="/static/css/detail.css?v=20190918.07" rel="stylesheet">
    <link href="/static/css/monokai.css?v=20190910.2" rel="stylesheet">
    <link href="/static/css/base_comment.css?v=20190114.554" rel="stylesheet">

    <!--根据cookies判断是否启用暗色主题-->

</head>
<body>
<!--导航开始-->

<nav class="navbar navbar-expand-md bg-white fixed-top blog-navbar py-md-0">
    <a class="navbar-brand d-md-none d-lg-block" id="site-logo-name" href="/">
        <strong class="px-2">TendCode</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-2">

                <a class="nav-link py-md-3 active" href="/"><i class="fa fa-home mr-1"></i>首页<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-2">

                <a class="nav-link py-md-3 " href="./archive.html"><i class="fa fa-sitemap mr-1"></i>归档</a>
            </li>

            <li class="nav-item mr-2">

                <a class="nav-link py-md-3 " href="/tool/"><i class="fa fa-balance-scale mr-1"></i>在线工具</a>
            </li>


            <li class="nav-item mr-2 d-none d-lg-block">
                <a class="nav-link py-md-3" href="https://hao.tendcode.com" target="_blank"><i
                        class="fa fa-chrome mr-1"></i>微草导航</a>
            </li>


            <li class="nav-item mr-2 ">

                <a class="nav-link py-md-3 " href="/about/"><i class="fa fa-anchor mr-1"></i>关于</a>
            </li>
            <form class="nav-item navbar-form mr-2 py-md-2" role="search" method="get" id="searchform"
                  action="/search/">
                <div class="input-group">
                    <input type="search" name="q" class="form-control rounded-0" placeholder="站内搜索" autocomplete="off"
                           required=True>
                    <div class="input-group-btn">
                        <button class="btn btn-info rounded-0" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </div><!-- /input-group -->
            </form>
        </ul>
        <ul class="navbar-nav">

            <li class="nav-item mr-2">
                <a class="nav-link py-md-3" href="/accounts/login/?next=/">登录</a>
            </li>
            <li class="nav-item">
                <a class="nav-link py-md-3" href="/accounts/signup/?next=/">注册</a>
            </li>

        </ul>
    </div>
</nav>

<!--导航结束-->

<!--消息块-->


<!--回到顶部按钮-->
<div class="text-center" id="to-top">
    <i class="fa fa-chevron-up" id="btn-top" title="回到顶部"></i>
</div>

<!--主要内容块-->
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9 col-xl-10">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-white border-0 rounded-0 mb-2 py-2 f-15">
                        <li class="breadcrumb-item">
                            <i class="fa fa-home mr-1"></i><a href="/">首页</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="/category/{{ art.category.id }}">{{ art.category.name }}</a>
                        </li>
                        <li class="breadcrumb-item active d-none d-md-block" aria-current="page">{{ art.title }}</li>
                        <li class="breadcrumb-item active d-md-none" aria-current="page">当前位置</li>
                    </ol>
                </nav>
                <div class="card rounded-0 border-0" id="article">
                    <div class="card-body px-2 px-md-3 pb-0">
                        <h1 class="card-title text-center font-weight-bold text-info">{{ art.title }}</h1>
                        <hr>
                        <div class="text-center f-13">
                            <span class="mx-2" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="最后编辑于{{ art.update_time }}">{{ art.update_time }}</span>
                            <span class="mx-2">阅读 {{ art.read_count }}</span>
                            <a class="mx-2 to-com" href="#comment-block">评论 20</a>
                        </div>



                         <div class="article-body mt-4 f-17" style="line-height:1.8">
                             {{ art.content }}

                         </div>
                        <div class="tag-cloud my-4">

                            <a class="tags f-16" href="/tag/Web-development/">后端开发</a>

                            <a class="tags f-16" href="/tag/Django/">Django</a>

                        </div>
                        <nav class="more-page f-16">
                            <ul class="pagination justify-content-between">
                                <li class="page-item">

                                    <a class="d-none d-md-block" href="/article/ansible-and-docker/" title="上一篇：使用 Ansible 工具批量操作虚拟机集群，自动化安装 Docker">
                                        <i class="fa fa-chevron-left mr-1"></i>
                                        使用 Ansible 工具批量操作虚
                                    </a>
                                    <a class="d-md-none" href="/article/ansible-and-docker/">
                                        <i class="fa fa-chevron-left mr-1"></i>上一篇</a>

                                </li>
                                <li class="page-item">

                                    <a class="d-none d-md-block" href="/article/python-shell-cmd/" title="下一篇：使用 python 执行 shell 命令的几种常用方式">
                                        使用 python 执行 shell
                                        <i class="fa fa-chevron-right ml-1"></i>
                                    </a>
                                    <a class="d-md-none" href="/article/python-shell-cmd/">
                                        下一篇<i class="fa fa-chevron-right ml-1"></i>
                                    </a>

                                </li>
                            </ul>
                        </nav>

                        <div class="text-center">
                            <button class="btn btn-danger rounded-0" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false" aria-controls="sponsor-zfb sponsor-wx" style="line-height: 1;font-size: .8rem;">
                                <i class="fa fa-cny"></i>
                                如果文章对你有所帮助，可以赞助本站
                                <i class="fa fa-chevron-down"></i>
                            </button>
                        </div>
                        <div class="row p-3">
                            <div class="col text-center">
                                <div class="collapse multi-collapse" id="sponsor-wx">
                                    <div class="p-1 text-success">微信</div>
                                    <img class="w-75" src="/static/blog/img/reward_wx.png">
                                </div>
                            </div>
                            <div class="col text-center">
                                <div class="collapse multi-collapse" id="sponsor-zfb">
                                    <div class="p-1 text-primary">支付宝</div>
                                    <img class="w-75" src="/static/blog/img/reward_zfb.png">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>
    <!--图片预览-->
    <div class="modal fade" id="img-to-big" tabindex="-1" role="dialog" aria-labelledby="img-to-bigTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 90%">
            <img class="rounded mx-auto d-block" alt="image" style="max-width: 100%">
        </div>
    </div>
    <!--前后文章-->

    <div class="more-blog" id="icon-pre-blog">
        <a href="/article/ansible-and-docker/">
            <i class="fa fa-angle-left fa-3x"></i>
        </a>
    </div>


    <div class="more-blog" id="icon-next-blog">
        <a href="/article/python-shell-cmd/">
            <i class="fa fa-angle-right fa-3x"></i>
        </a>
    </div>

</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<!--js cookie 插件-->
<script src="/static/js/js.cookie.min.js?v=20191123.12"></script>
<script src="https://cdn.bootcss.com/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script>
    $(function () {
        var myElement = document.querySelector(".blog-navbar");
        var headroom = new Headroom(myElement);
        headroom.init()
    });
</script>
<script src="/static/js/base.js?v=20191123.0909890"></script>


<footer class="container-fluid mt-4 py-0">
    <div class="card-body text-center px-0 f-14">
        <p class="card-text mb-1">Copyright&nbsp;&copy;&nbsp;<span id="year-info"></span>
            &nbsp;Powered&nbsp;by&nbsp;Django.
        </p>


    </div>
</footer>
</body>
</html>

day19/sky/templates/fubiao.html
<h2 style="color: #00AAEE">浮标</h2>

day19/sky/templates/lhy.html
{% extends 'nhy.html' %}

{% block body %}

    {% include 'fubiao.html' %}
    <ul>
    <li>刘海洋</li>
    <li>方丹</li>
    <li>高雯</li>
    <li>代爽</li>
    </ul>
    {% include 'fubiao.html' %}

{% endblock %}

day19/sky/templates/nhy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>头部 -- nhy</h1>

{% block body %}
<h1>腰部</h1>
{% endblock %}

<h1>尾部 --- nhy</h1>

</body>
</html>

day19/sky/templates/template_tags.html
{% load my_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模板标签</title>
</head>
<body>

<p>{{ content|truncatechars:30 }}</p>
{#截取字符串#}


<p>{{ content|mingan}}</p>

<p>{{ content|mingan2:'大傻子'}}</p>

<p>{% mingan3 content 'sb' 'SB' '金三胖' '三胖'  %}</p>


<p>{{ title|upper }}</p>
<p>{{ title|lower }}</p>
<p>{{ stus.0 }}</p>
{#list取下标#}
<p>{{ stus|length }}</p>
{#取list的长度#}
<p>{{ stus|slice:"0:2" }}</p>
{#切片#}
<p>{{ stus|join:"-" }}</p>
{#拼接#}

<p>{{ info.money }}</p>
{#字典取值#}

<p>{{ name|add:"，你好" }}</p>
{#字符串拼接#}
<p>{{ age|add:1 }}</p>
{#int类型就是相加#}
<p>{{ cur_date|date:"Y-m-d H:i:s" }}</p>

{% with class="天马座" %}
<p>{{ class }}</p>
{% endwith %}
{#在模板里面定义变量#}

</body>
</html>